"""
The palette. Every colour on the site is defined here once and nowhere else.

Two copies of the palette used to exist, one inside theme.py for the generated pages and one
hardcoded in site/index.html for the map, so every change had to be made twice and they drifted.
The build now writes site/palette.css from this file; both the static pages and the map load it,
and the map's JavaScript reads its category colours out of the same custom properties instead of
keeping its own table of hex values.

Two rules:
  1. Interface is paper, ink and rules. No hue. A colour on screen always means a category.
  2. Every category colour has to be distinguishable from every other at the size of a legend
     swatch. OFAC SDN and OFAC other used to be two nearly identical oranges.
"""

# ---- interface: no hue at all
UI = {
    "bg":      "#f4f4f1",   # paper
    "bg-2":    "#ffffff",   # raised surfaces
    "bg-3":    "#eaeae6",   # sunk surfaces, code, inputs
    "ink":     "#16181a",   # body text, primary buttons
    "ink-2":   "#55595e",   # secondary text
    "ink-3":   "#8a8f95",   # metadata
    "line":    "#dddcd5",   # hairlines
    "line-2":  "#bebdb4",   # stronger borders
    # kept under their old names because other files reference them; all point at ink now
    "accent":      "#16181a",
    "accent-2":    "#3a3e42",
    "accent-fill": "#16181a",
    # the only non-category colours: something worked, something broke
    "good":    "#2e7d5b",
    "bad":     "#a03227",
    "blue":    "#2f5fb5",
    # map surfaces
    "water":   "#aec9e2",
    "land":    "#f1f0ea",
}

# ---- categories: one hue each, all separable at swatch size
DATA = {
    "c-ofac-sdn":    "#c2571a",
    "c-ofac-other":  "#7a4a28",   # was a second orange, now brown
    "c-bis-entity":  "#1b7a8c",
    "c-bis-other":   "#2e7d5b",
    "c-state":       "#6a4c93",
    "c-eu":          "#2f5fb5",
    "c-uk":          "#b0367a",
    "c-un":          "#4a5568",
    "c-au":          "#7e9b2e",   # olive, so it does not read as BIS green
    "c-ca":          "#c0392b",
    "c-ch":          "#c8a227",
    "c-jp":          "#0b3d91",
    # not categories: structure drawn over the map, deliberately neutral so it never
    # competes with a category colour
    "c-cluster":     "#8a8f95",
    "c-corridor":    "#6f7377",
    "c-corridor-hi": "#3a3e42",
    "c-added":       "#2e7d5b",
    "c-cmp-a":       "#1b7a8c",
    "c-cmp-b":       "#c2571a",
    "c-cmp-both":    "#2e7d5b",
}

def root_block(indent=""):
    """The :root rule, for inlining into a <style> block."""
    items = list(UI.items()) + list(DATA.items())
    lines, cur = [], indent + ":root{"
    for k, v in items:
        piece = f"--{k}:{v};"
        if len(cur) + len(piece) > 118:
            lines.append(cur); cur = indent + "      "
        cur += piece
    lines.append(cur.rstrip(";") + "}")
    return "\n".join(lines)

def stylesheet():
    """The standalone file both the map and the generated pages load."""
    return ("/* Generated by pipeline/palette.py. Do not edit by hand: change the palette there\n"
            "   and it applies to the map and every static page at once. */\n"
            + root_block() + "\n")

if __name__ == "__main__":
    print(stylesheet())
